
import { Inter } from "next/font/google";
import "./globals.css";
import "@/app/css/navbar.css";
import "@/app/css/loader.css";
import Navbarr from "../../components/navbar/Navbarr";
import Provider from "../configs/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Navbarr />
          {children}
        </Provider>
      </body>
    </html>
  );
}
